### ISSUE TITLE
num classes

### ISSUE THREAD

**Issue by wsready** [lywa1998/FedDG#3]
请问眼底数据集的num_classes是三吗

**Comment by ptrdlr14** [comment]
这篇论文中使用眼底数据集是做的图像分割任务，而不是图像分类。

**Comment by wsready** [comment]
train脚本75行说是num_classes为3

**Comment by ptrdlr14** [comment]
这是一个未使用的变量。可能论文作者有其他用途，但在这片论文研究中我没看到用处。

**Comment by wsready** [comment]
你的dice是多少呢 我跑出来只有1点几，我用的自己的数据集

**Comment by ptrdlr14** [comment]
好像比原论文中的结果差4-5%左右。你这1点几应该有问题吧

**Comment by wsready** [comment]
好，谢谢  Epoch: [64] client [0] iteration [10 / 58] : inner loss : -0.488420 outer dice loss : -0.486812 outer cont loss : 7.783448 outer loss : 0.291533 total loss : -0.196886   有一些loss是负的  这是正常的吗

**Comment by ptrdlr14** [comment]
我看了下应该不会有负值，inner loss在论文和代码中都是用的是Dice Loss函数

**Comment by wsready** [comment]
好，感谢您，估计是我数据处理的问题 我再看下吧

**Comment by gitCoder1024** [comment]
dice的取值范围是0-1之间，我跑出来dice也是大于1，这应该是有问题的吧
