### ISSUE TITLE
Result on the Unseen Site

### ISSUE THREAD

**Issue by XLoveRye** [lywa1998/FedDG#4]
lywa1998，您好

非常感谢您的开源代码！我在Fundus数据集上用FedDG跑出来的结果和其论文中汇报的结果有一定差距，我的结果（avg dice value of OC&OD）具体如下：
client0 (domain1): 83.51%
client1 (domain2): 68.31%
client2 (domain3): 84.75%
client3 (domain4): 85.84%
请问您能否告知我您当时跑出来的具体结果呢？我想对比一下，谢谢！

**Comment by ptrdlr14** [comment]
由于时间比较长，目前我只找到留下来的数据是：gamma = 0.1 时， OD：86%，OC：84%。gamma = 0.01 时最好效果是OD：87%，OC：85%，不过在 gamma = 0.01 时，可能是我学习率设的有点高，训练后期精度会降低的现象。由于当时的具体参数记不清了，但大概率是论文中提供的 1e-3。
